CREATE TABLE coupon_instances (
    id                 BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    template_id        BIGINT UNSIGNED NOT NULL,
    user_phone         VARCHAR(20)     NOT NULL COMMENT 'User phone number',
    source_store_id    BIGINT UNSIGNED NOT NULL COMMENT 'Which store issued this coupon',
    coupon_code        VARCHAR(64)     NOT NULL COMMENT 'Unique coupon code',
    status             ENUM('unused','used','expired','frozen')
                                       NOT NULL DEFAULT 'unused',
    receive_time       DATETIME        NOT NULL COMMENT 'When user received the coupon',
    use_time           DATETIME        DEFAULT NULL,
    used_at_store_id   BIGINT UNSIGNED DEFAULT NULL,
    use_order_id       VARCHAR(64)     DEFAULT NULL COMMENT 'Order ID for refund validation',
    use_order_amount   DECIMAL(10,2)   DEFAULT NULL COMMENT 'Order amount for refund validation',
    valid_start        DATETIME        NOT NULL COMMENT 'Effective validity start',
    valid_end          DATETIME        NOT NULL COMMENT 'Effective validity end',
    idempotency_key    VARCHAR(128)    DEFAULT NULL COMMENT 'Business idempotency key',
    version            INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT 'Optimistic lock',
    created_at         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_coupon_code (coupon_code),
    UNIQUE KEY uk_idempotency (source_store_id, idempotency_key),
    KEY idx_user_phone (user_phone),
    KEY idx_user_phone_status (user_phone, status),
    KEY idx_template_id (template_id),
    KEY idx_source_store (source_store_id),
    KEY idx_used_store (used_at_store_id),
    KEY idx_valid_end (valid_end),
    KEY idx_receive_time (receive_time),
    CONSTRAINT fk_ci_template FOREIGN KEY (template_id) REFERENCES coupon_templates(id),
    CONSTRAINT fk_ci_source_store FOREIGN KEY (source_store_id) REFERENCES stores(id),
    CONSTRAINT fk_ci_used_store FOREIGN KEY (used_at_store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Coupon instances issued to users';
